repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.10
  hooks:
    - id: ruff-check
      args: [ --select, I, --fix ] # include import sort
    - id: ruff-check
      args: [ --fix ] 
    - id: ruff-format
